#include "Asset/EmbedAsset.hpp"

#include <filesystem>
#include <iomanip>
#include <sstream>

#include "Asset/Texture.hpp"
#include "Core/App.hpp"
#include "OS/File.hpp"
#include "OS/OS.hpp"
#include "Utils/Log.hpp"

namespace ox {

auto EmbedAsset::embed_texture(
  const std::string& tex_file_path, const std::string& out_path, const std::string& array_name
) -> void {
  u32 width = 0, height = 0, bits = 0;
  const auto texture = Texture::load_stb_image(tex_file_path, &width, &height, &bits);

  if (!texture) {
    OX_LOG_ERROR("Failed to load texture from: {}", tex_file_path);
    return;
  }

  const u32 psize = width * height * 4;
  std::stringstream ss;

  ss << "// Generated by Oxylus Engine\n";
  ss << "// Source: " << std::filesystem::path(tex_file_path).filename().string() << "\n";
  ss << "// Size: " << width << "x" << height << " (" << bits << " bits per pixel)\n";
  ss << "#pragma once\n\n";
  ss << "#include <cstdint>\n\n";
  ss << "namespace ox::embedded {\n\n";

  ss << "static constexpr uint32_t " << array_name << "_width = " << width << ";\n";
  ss << "static constexpr uint32_t " << array_name << "_height = " << height << ";\n";
  ss << "static constexpr uint32_t " << array_name << "_bits = " << bits << ";\n";
  ss << "static constexpr uint32_t " << array_name << "_size = " << psize << ";\n\n";

  ss << "static constexpr uint8_t " << array_name << "_data[] = {\n  ";

  constexpr usize values_per_line = 16;
  for (usize i = 0; i < psize; ++i) {
    ss << "0x" << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(texture[i]);

    if (i != psize - 1) {
      ss << ",";
      if ((i + 1) % values_per_line == 0)
        ss << "\n  ";
      else
        ss << " ";
    }
  }

  ss << "\n};\n\n";
  ss << "} // namespace ox::embedded\n";

  auto file = File(out_path, FileAccess::Write);
  file.write(ss.str());
  file.close();

  OX_LOG_INFO(
    "Successfully embedded texture '{}' -> '{}' ({}x{}, {} bytes)",
    tex_file_path,
    out_path,
    width,
    height,
    psize
  );
}

auto EmbedAsset::embed_shader(
  const std::string& shader_path, const std::string& out_path, const std::string& entry_point
) -> void {
  auto& vfs = App::get_vfs();
  auto shaders_dir = vfs.resolve_physical_dir(VFS::APP_DIR, "Shaders");
  const auto full_shader_path = shaders_dir / shader_path;
  if (!std::filesystem::exists(full_shader_path)) {
    OX_LOG_ERROR("Shader file not found: {}", full_shader_path.string());
    return;
  }

  auto slang_global_session = SlangCompiler::create();
  if (!slang_global_session.has_value()) {
    return;
  }
  auto slang_session = slang_global_session->new_session({.root_directory = shaders_dir});
  if (!slang_session.has_value()) {
    return;
  }

  OX_DEFER(&) {
    if (slang_global_session.has_value())
      slang_global_session->destroy();
    if (slang_session.has_value())
      slang_session->destroy();
  };

  auto compiled_entry_points = slang_session->compile_shader({.module_name = "main", .entry_points = {entry_point}});
  if (!compiled_entry_points.has_value()) {
    OX_LOG_ERROR("Failed to compile shader: {}", shader_path);
    return;
  }

  auto& shader = compiled_entry_points->front();
  const auto& spirv_data = shader.code;
  const u32 spirv_size = shader.code.size();

  if (spirv_size == 0) {
    OX_LOG_ERROR("Compiled shader is empty: {}", shader_path);
    return;
  }

  std::filesystem::path shader_file_path(shader_path);
  std::string base_name = shader_file_path.stem().string();
  std::string array_name = base_name + "_" + entry_point;

  // Sanitize array name
  for (auto& c : array_name) {
    if (!std::isalnum(c))
      c = '_';
  }

  std::stringstream ss;
  ss << "// Generated by Oxylus Engine\n";
  ss << "// Source: " << shader_file_path.filename().string() << "\n";
  ss << "// Entry Point: " << entry_point << "\n";
  ss << "// SPIR-V Size: " << spirv_size << " bytes (" << spirv_data.size() << " words)\n";
  ss << "#pragma once\n\n";
  ss << "#include <cstdint>\n\n";
  ss << "namespace ox::embedded {\n\n";

  ss << "static constexpr uint32_t " << array_name << "_size = " << spirv_size << ";\n";
  ss << "static constexpr uint32_t " << array_name << "_word_count = " << spirv_data.size() << ";\n\n";

  ss << "static constexpr uint32_t " << array_name << "_spirv[] = {\n  ";

  constexpr usize words_per_line = 8;
  for (usize i = 0; i < spirv_data.size(); ++i) {
    ss << "0x" << std::hex << std::setw(8) << std::setfill('0') << spirv_data[i];

    if (i != spirv_data.size() - 1) {
      ss << ",";
      if ((i + 1) % words_per_line == 0)
        ss << "\n  ";
      else
        ss << " ";
    }
  }

  ss << "\n};\n\n";
  ss << "} // namespace ox::embedded\n";

  auto file = File(out_path, FileAccess::Write);
  file.write(ss.str());
  file.close();

  OX_LOG_INFO(
    "Successfully embedded shader '{}' (entry: '{}') -> '{}' ({} bytes)",
    shader_path,
    entry_point,
    out_path,
    spirv_size
  );
}

auto EmbedAsset::embed_binary(
  const std::string& binary_path, const std::string& out_path, const std::string& array_name
) -> void {
  const auto binary_data = File::to_bytes(binary_path);
  if (binary_data.empty()) {
    OX_LOG_ERROR("Binary file is empty: {}", binary_path);
    return;
  }

  std::stringstream ss;
  ss << "// Generated by Oxylus Engine\n";
  ss << "// Source: " << std::filesystem::path(binary_path).filename().string() << "\n";
  ss << "// Size: " << binary_data.size() << " bytes\n";
  ss << "#pragma once\n\n";
  ss << "#include <cstdint>\n\n";
  ss << "namespace ox::embedded {\n\n";

  ss << "static constexpr uint64_t " << array_name << "_size = " << binary_data.size() << ";\n\n";
  ss << "static constexpr uint8_t " << array_name << "_data[] = {\n  ";

  constexpr usize bytes_per_line = 16;
  for (usize i = 0; i < binary_data.size(); ++i) {
    ss << "0x" << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(binary_data[i]);

    if (i != binary_data.size() - 1) {
      ss << ",";
      if ((i + 1) % bytes_per_line == 0)
        ss << "\n  ";
      else
        ss << " ";
    }
  }

  ss << "\n};\n\n";
  ss << "} // namespace ox::embedded\n";

  auto out_file = File(out_path, FileAccess::Write);
  out_file.write(ss.str());
  out_file.close();

  OX_LOG_INFO("Successfully embedded binary '{}' -> '{}' ({} bytes)", binary_path, out_path, binary_data.size());
}

} // namespace ox
