#include "Asset/EmbedAsset.hpp"

#include <filesystem>
#include <iomanip>
#include <sstream>

#include "OS/File.hpp"
#include "OS/OS.hpp"
#include "Utils/Log.hpp"

namespace ox {
auto EmbedAsset::embed_texture(
  const std::string& tex_file_path, const std::string& out_path, const std::string& array_name
) -> void {
  OX_LOG_ERROR(
    "EmbedAsset::embed_texture is no longer supported. Use the ResourceCompiler to compile shaders offline."
  );
}

auto EmbedAsset::embed_shader(
  const std::string& shader_path, const std::string& out_path, const std::string& entry_point
) -> void {
  OX_LOG_ERROR("EmbedAsset::embed_shader is no longer supported. Use the ResourceCompiler to compile shaders offline.");
}

auto EmbedAsset::embed_binary(
  const std::string& binary_path, const std::string& out_path, const std::string& array_name
) -> void {
  const auto binary_data = File::to_bytes(binary_path);
  if (binary_data.empty()) {
    OX_LOG_ERROR("Binary file is empty: {}", binary_path);
    return;
  }

  std::stringstream ss;
  ss << "// Generated by Oxylus Engine\n";
  ss << "// Source: " << std::filesystem::path(binary_path).filename().string() << "\n";
  ss << "// Size: " << binary_data.size() << " bytes\n";
  ss << "#pragma once\n\n";
  ss << "#include <cstdint>\n\n";
  ss << "namespace ox::embedded {\n\n";

  ss << "static constexpr uint64_t " << array_name << "_size = " << binary_data.size() << ";\n\n";
  ss << "static constexpr uint8_t " << array_name << "_data[] = {\n  ";

  constexpr usize bytes_per_line = 16;
  for (usize i = 0; i < binary_data.size(); ++i) {
    ss << "0x" << std::hex << std::setw(2) << std::setfill('0') << static_cast<int>(binary_data[i]);

    if (i != binary_data.size() - 1) {
      ss << ",";
      if ((i + 1) % bytes_per_line == 0)
        ss << "\n  ";
      else
        ss << " ";
    }
  }

  ss << "\n};\n\n";
  ss << "} // namespace ox::embedded\n";

  auto out_file = File(out_path, FileAccess::Write);
  out_file.write(ss.str());
  out_file.close();

  OX_LOG_INFO("Successfully embedded binary '{}' -> '{}' ({} bytes)", binary_path, out_path, binary_data.size());
}

} // namespace ox
