version = 10

[[shader_sessions]]
root_directory = "../../Oxylus/src/Render/Shaders"
session_name = "engine"
debug_symbols = false
optimization = "default"

[[shader_sessions.programs]]
name = "rmlui"
path = "passes/rmlui.slang"
entry_points = ["vs_main", "fs_main"]

[[shader_sessions.programs]]
name = "2d_forward"
path = "passes/2d_forward.slang"
entry_points = ["vs_main", "fs_main"]
bindless = true

[[shader_sessions.programs]]
name = "2d_forward_vis"
path = "passes/2d_forward_vis.slang"
entry_points = ["vs_main", "fs_main"]
bindless = true

[[shader_sessions.programs]]
name = "sky_transmittance"
path = "passes/sky_transmittance.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "2d_forward_vis"
path = "passes/2d_forward_vis.slang"
entry_points = ["vs_main", "fs_main"]
bindless = true

[[shader_sessions.programs]]
name = "sky_multiscatter"
path = "passes/sky_multiscattering.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "sky_view"
path = "passes/sky_view.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "sky_aerial_perspective"
path = "passes/sky_aerial_perspective.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "cull_meshes"
path = "passes/cull_meshes.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "cull_meshlets"
path = "passes/cull_meshlets.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "cull_meshlets_hiz"
path = "passes/cull_meshlets_hiz.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "cull_triangles"
path = "passes/cull_triangles.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "visbuffer_encode"
path = "passes/visbuffer_encode.slang"
entry_points = ["vs_main", "fs_main"]
bindless = true

[[shader_sessions.programs]]
name = "visbuffer_clear"
path = "passes/visbuffer_clear.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "visbuffer_decode"
path = "passes/visbuffer_decode.slang"
entry_points = ["vs_main", "fs_main"]
bindless = true

[[shader_sessions.programs]]
name = "shadowmap_draw"
path = "passes/shadowmap_draw.slang"
entry_points = ["vs_main", "fs_main"]

[[shader_sessions.programs]]
name = "rmvsm_allocate_pages"
path = "passes/rmvsm_allocate_pages.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "rmvsm_clear_dirty_pages"
path = "passes/rmvsm_clear_dirty_pages.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "rmvsm_downsample_hpb"
path = "passes/rmvsm_downsample_hpb.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "rmvsm_draw_physical_pages"
path = "passes/rmvsm_draw_physical_pages.slang"
entry_points = ["vs_main", "fs_main"]

[[shader_sessions.programs]]
name = "rmvsm_free_invisible_pages"
path = "passes/rmvsm_free_invisible_pages.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "rmvsm_invalidate_pages"
path = "passes/rmvsm_invalidate_pages.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "rmvsm_mark_dirty_pages"
path = "passes/rmvsm_mark_dirty_pages.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "rmvsm_mark_visible_pages"
path = "passes/rmvsm_mark_visible_pages.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "rmvsm_reset_page_visibility"
path = "passes/rmvsm_reset_page_visibility.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "resolve_shadowmaps"
path = "passes/resolve_shadowmaps.slang"
entry_points = ["vs_main", "fs_main"]

[[shader_sessions.programs]]
name = "debug_view"
path = "passes/debug_view.slang"
entry_points = ["vs_main", "fs_main"]

[[shader_sessions.programs]]
name = "pbr_apply"
path = "passes/pbr_apply.slang"
entry_points = ["vs_main", "fs_main"]

[[shader_sessions.programs]]
name = "hiz"
path = "passes/hiz.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "histogram_generate"
path = "passes/histogram_generate.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "histogram_average"
path = "passes/histogram_average.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "tonemap"
path = "passes/tonemap.slang"
entry_points = ["vs_main", "fs_main"]

[[shader_sessions.programs]]
name = "bloom_prefilter"
path = "passes/bloom_prefilter.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "bloom_downsample"
path = "passes/bloom_downsample.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "bloom_upsample"
path = "passes/bloom_upsample.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "vbgtao_prefilter"
path = "passes/gtao/vbgtao_prefilter.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "vbgtao_main"
path = "passes/gtao/vbgtao_main.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "vbgtao_denoise"
path = "passes/gtao/vbgtao_denoise.slang"
entry_points = ["cs_main"]

[[shader_sessions.programs]]
name = "fxaa"
path = "passes/fxaa/fxaa.slang"
entry_points = ["vs_main", "fs_main"]

[[shader_sessions.programs]]
name = "debug_mesh"
path = "passes/debug_mesh.slang"
entry_points = ["vs_main", "fs_main"]

[[shader_sessions.programs]]
name = "contact_shadows"
path = "passes/contact_shadows.slang"
entry_points = ["cs_main"]
