// generated by ecsgen from Fixture.hpp, do not edit

#include <array>

#include "Asset/AssetFile.hpp"
#include "Scene/ComponentRegistry.hpp"
#include "Scene/Components.hpp"

namespace ox {
static auto bind_fixture_components(ox::ComponentRegistry& registry) -> void {
  registry.bind_enum<EnumComponent::Mode>("EnumMode");
  registry.bind_enum<EnumComponent::Forced>("EnumForced");
  registry.bind_enum<EnumComponent::Kind>("Kind");

  {
    using C = PlainComponent;
    registry.bind<
      &C::a,
      &C::b,
      &C::rotation,
      &C::weights,
      &C::color>("Renamed")
      .tags<ox::Networked>();
  }

  {
    using C = EnumComponent;
    static constexpr auto asset_fields = std::array{
      ox::AssetField{"texture", ox::AssetType::Texture},
    };
    registry.bind<&C::mode, &C::kind, &C::texture>()
      .asset_fields(asset_fields);
  }
}
} // namespace ox
