// generated by ecsgen from Fixture.hpp, do not edit

#include <array>

#include "Asset/AssetFile.hpp"
#include "Scene/ComponentRegistry.hpp"
#include "Scene/Components.hpp"

namespace ox {
static auto bind_fixture_components(ox::ComponentRegistry& registry) -> void {
  registry.bind_enum<EnumComponent::Mode>("EnumMode");
  registry.bind_enum<EnumComponent::Forced>("EnumForced");
  registry.bind_enum<EnumComponent::Kind>("Kind");
  registry.bind_enum<EnumComponent::Shape>("EnumShape");
  registry.bind_enum<EnumComponent::Side>("EnumSide");

  {
    using C = PlainComponent;
    registry.bind<
      &C::a,
      &C::b,
      &C::rotation,
      &C::weights,
      &C::color,
      &C::aligned,
      &C::sized,
      &C::callback>("Renamed")
      .tags<ox::Networked>();
  }

  {
    using C = EnumComponent;
    static constexpr auto asset_fields = std::array{
      ox::AssetField{"texture", ox::AssetType::Texture},
      ox::AssetField{"model", ox::AssetType::Model},
      ox::AssetField{"prefab", ox::AssetType::Scene},
    };
    registry.bind<
      &C::mode,
      &C::kind,
      &C::shape,
      &C::side,
      &C::texture,
      &C::model,
      &C::prefab>()
      .asset_fields(asset_fields);
  }
}
} // namespace ox
